# Generated by Django 6.0.2 on 2026-02-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['-zona_horaria'], 'verbose_name': 'perfil', 'verbose_name_plural': 'perfils'},
        ),
        migrations.AlterModelTable(
            name='perfil',
            table='perfil',
        ),
    ]
