# Generated by Django 6.0.2 on 2026-02-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='disponibilidad',
            field=models.TextField(default='Add your availability here\nAñade tu disponibilidad aquí'),
        ),
    ]
