# Generated by Django 6.0.2 on 2026-02-27 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_perfil_zona_horaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdo',
            name='usuario_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acuerdos_b', related_query_name='acuerdo_b', to=settings.AUTH_USER_MODEL),
        ),
    ]
