# Generated by Django 6.0.2 on 2026-02-27 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_acuerdo_usuario_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuerdo',
            name='publicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acuerdos', related_query_name='acuerdo', to='core.publicacion'),
        ),
    ]
