# Generated by Django 6.0.2 on 2026-02-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_acuerdo_publicacion'),
        ('core', '0004_acuerdo_publicacion_alter_perfil_zona_horaria'),
    ]

    operations = [
    ]
