# Generated by Django 6.0.2 on 2026-02-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_perfil_zona_horaria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidad',
            options={'ordering': ['nombre'], 'verbose_name': 'habilidad', 'verbose_name_plural': 'habilidades'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ('usuario',), 'verbose_name': 'perfil', 'verbose_name_plural': 'perfiles'},
        ),
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ('-fecha_creacion',), 'verbose_name': 'publicacion', 'verbose_name_plural': 'publicaciones'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
