name: Bug report 🐛
description: Report a bug
title: "[Bug] "
labels: ["bug"]

body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
      default: 1
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Describe the bug clearly
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: What happens
      description: What is currently happening?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected
      description: What should happen instead?
    validations:
      required: true