name: Documentation 📚
description: Improve or add documentation
title: "[Docs] "
labels: ["documentation"]

body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
      default: 1
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What needs documentation?
      description: README, docstrings, comments, templates...
      placeholder: Add API endpoint docs to README.md
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where should the documentation be added?
      placeholder: README.md, core/models.py docstrings, etc.